development:
  adapter: mysql2
  encoding: utf8
  database: grape_development
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>

test:
  adapter: mysql2
  encoding: utf8
  database: grape_test
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>

production:
  adapter: mysql2
  encoding: utf8
  database: grape_production
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
